### ISSUE TITLE
Cannot fetch an artifact without s3:ListAllMyBuckets policy action

### ISSUE THREAD

**Issue by charliepben** [gkatzioura/CloudStorageMaven#18]
Hi,

Thanks for this cool extension! ❤
I am experiencing one little issue though, I am not able to fetch an artifact without the very permission :

> s3:ListAllMyBuckets

I tested with the same user, connected to the console UI I am able to browse and download, but if I remove this specific permission, s3-storage-wagon cannot fetch anymore my artifacts.

It's a permission I would prefer not to set to all my users as they should not be capable of seeing my other buckets.

Did anyone notice that? 

Thanks,

Charlie

**Comment by ywilkof** [comment]
I was able to reproduce this as well.
Seems like this is the fix: https://github.com/mstump/CloudStorageMaven/commit/4dbcf4dd87805b4e654492c71e41c86a84ed243d

**Comment by gkatzioura** [comment]
This should be resolved on version 1.9

<dependency>
  <groupId>com.gkatzioura.maven.cloud</groupId>
  <artifactId>s3-storage-wagon</artifactId>
  <version>1.9</version>
</dependency>
