### ISSUE TITLE
List bucket not buckets when checking GCS permissions

### ISSUE THREAD

**Issue by mstump** [gkatzioura/CloudStorageMaven#2]
Listing buckets to test GCS permissions requires elevated permissions as compared to listing the contents of the single bucket used for publishing. By [listing only the single bucket](https://github.com/mstump/CloudStorageMaven/commit/4dbcf4dd87805b4e654492c71e41c86a84ed243d) it's easier to use this library in high security environments.

**Comment by Artgit** [comment]
+1  Could you please fix it and made a new release?

**Comment by gkatzioura** [comment]
Changes merged. New version 1.2 has the fix.
