### ISSUE TITLE
'key' local variable is never used

### ISSUE THREAD

**Issue by fnoguier** [gkatzioura/CloudStorageMaven#21]
Hi,

https://github.com/gkatzioura/CloudStorageMaven/blob/6217b46269012b11e81e04d4195fc5862490b8ec/GoogleStorageWagon/src/main/java/com/gkatzioura/maven/cloud/gcs/GoogleStorageRepository.java#L129

shouldn't it be : 

     Blob blob = storage.get(bucket, key); 

instead, at the moment the 'key' local variable is never used.

**Comment by gkatzioura** [comment]
Hi! Thanks for finding this. Will act accordingly.

**Comment by gkatzioura** [comment]
Changed on version 1.6
