### ISSUE TITLE
s3-storage-wagon store artifacts for public read

### ISSUE THREAD

**Issue by leviathan747** [gkatzioura/CloudStorageMaven#25]
Is it possible to add an option to publish artifacts to S3 with the ACL set to allow public read? This would allow users to download my artifacts without depending on the s3 storage wagon or having an access policy to my AWS account -- their projects could be simply set up with an HTTP link to the repository.

This would be as simple as adding `.withCannedAcl(CannedAccessControlList.PublicRead)` to the `PutObjectRequest` in the `S3StorageRepository` class. I'm not too familiar with maven extensions, so I don't know how/if it is possible to configure an extension with parameters to make this an option.

**Comment by gkatzioura** [comment]
It will be done with environmental variables, and probably an extra xml tag.

**Comment by gkatzioura** [comment]
Implemented it! Will be on the next release.
Since your artefacts are going to be public they can be accessed through plain http.

```xml
    <repositories>
        <repository>
            <id>my-repo-bucket-snapshot</id>
            <url>https://s3-eu-west-1.amazonaws.com/whatever/snapshot</url>
        </repository>
    </repositories>
```

**Comment by gkatzioura** [comment]
It is on version 1.8
Please use the documentation on to achieve public read repos. 
https://github.com/gkatzioura/CloudStorageMaven/tree/master/S3StorageWagon
Great feature, thanks for mentioning!
