### ISSUE TITLE
Checksum failures on version <= 1.7 replacing existing artifacts with google-storage-wagon

### ISSUE THREAD

**Issue by rvaidya** [gkatzioura/CloudStorageMaven#45]
Perhaps this is already fixed, but if I am replacing an existing object, like the index files for the package, I get the following:

[WARNING] Checksum validation failed, expected bb29bd78d7ea635bf96003a85e3294bd3c27578a but is da39a3ee5e6b4b0d3255bfef95601890afd80709 for gs://mvn.company.com/release/com/company/artifact/maven-metadata.xml

the da39... etc. checksum is the same for all files it tries to replace.

This might already be fixed in >= 1.8 but I cannot verify since uploads always fail with those versions, see #44

**Comment by gkatzioura** [comment]
Unfortunately I cannot fix this (well everything is pretty much functional, so no actual problem). The reason has to do will maven validations being based on streams and the google java sdk for the cloud storage that operates behind the scenes does not give access to an InputStream

**Comment by rvaidya** [comment]
If you need an InputStream from the google cloud SDK you can do something like:

```
BlobInfo.Builder blobInfoBuilder = BlobInfo.newBuilder(bucketName, resourceURI);
Blob content = _storage.get(blobInfoBuilder.build().getBlobId());
InputStream is = Channels.newInputStream(content.reader());
```
