### ISSUE TITLE
Content length not specified for S3 PutObject

### ISSUE THREAD

**Issue by blockmar** [gkatzioura/CloudStorageMaven#48]
Using this wagon with S3 results in multiple warnings:
```
WARNING: No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
```

From what I can tell by looking at the code the put operations are always preformed on `File` objects so the size should be known and we should be able to set it before uploading.

**Comment by raif-s-naffah** [comment]
hi there,

any ETA for a release that includes this fix?

**Comment by gkatzioura** [comment]
@raif-s-naffah 
Hi, there have been some technical issues. By the end of the month it shall be released.

**Comment by raif-s-naffah** [comment]
thanks!

FWIW i built locally a 2.1-snapshot (after commenting out the GPG plugin) and tested w/ a ~9MB artifact and (a) the warnings did not appear, and (b) progress messages re. uploading the artifacts were displayed instead.
