### ISSUE TITLE
S3StorageWagon: Make API credentials optional

### ISSUE THREAD

**Issue by duaraghav8** [gkatzioura/CloudStorageMaven#5]
Hi,

AWS allows an EC2 machine to access resources even when there aren't any API credentials present in the system, if the machine's IAM role contains permissions to access those resources.

It seems that S3StorageWagon makes providing API keys mandatory.
**Is there currently a way I can force it to ignore authenticating if the credentials are not provided?**

The API requests will still go through successfully because this wagon will be running in an EC2 machine that has IAM permissions to access the bucket, so API keys are not required.

If currently not possible, I'd like to submit a fix if you're open to it.

I'm using S3StorageWagon `v1.0`.

**Comment by gkatzioura** [comment]
resolved with version 1.2

**Comment by duaraghav8** [comment]
Thanks @gkatzioura
