### ISSUE TITLE
S2StorageMaven vs MinIO

### ISSUE THREAD

**Issue by lburgazzoli** [gkatzioura/CloudStorageMaven#65]
Was trying to use S2StorageMaven against my own MinIO instance but I didn't found a way to configure a custom endpoint even if it seems to be supported, is there any doc/example about that ?

**Comment by gkatzioura** [comment]
I think you need to try to set the S3_ENDPOINT environmental variable

**Comment by gkatzioura** [comment]
Sorry it is a system property (S3_ENDPOINT)

**Comment by lburgazzoli** [comment]
Found that you can either set a <endpoint> element in the server config or as you mentioned set a system property named S3_ENDPOINT
