### ISSUE TITLE
Is there a way to provide the "project" without configuring the gcloud cli?

### ISSUE THREAD

**Issue by swagatata** [gkatzioura/CloudStorageMaven#9]
Hi, 

We want to use this plugin in our source code to fetch dependencies from a GCP bucket. We cannot expect all machines running the build to have gcloud configured. Is there a way to pass the "project" name without configuring through gcloud cli?

Please help!

**Comment by gkatzioura** [comment]
What you need to have, is actually access to a google cloud credentials file. You can contain this file with your project however it is not advised. This is how google cloud operates. 
If your concern however has to do with machines spawned in google cloud then your need to create a service roles and you shall be fine.
https://egkatzioura.com/2018/04/09/host-your-maven-artifacts-using-google-cloud-storage/
